# Fall 2025 XC Schedule

Saturday September 6, Verona Invitational

- Meet info: https://crm.pttiming.com/uploads/projects/2452/0aa348f6771f09857f2b77a8f4ef72c6.pdf
- No bus
- Arrive at race at 10:15 am 
- Race starts at 11 am (single race)


Saturday September 13, Monona Grove Invitational 

- Meet info: ???
- No bus
- Arrive at race at ???
- First race starts at ???


[TBD] Saturday September 21, Wildcat Invitational, Belleville

- Meet info: ???
- Bus departs from O'Keeffe at ???
- First race starts at ???
- Bus returns to O'Keeffe at ???

[Optional] Saturday September 27, Midwest Invitational Blackhawk Golf Course, Janesville

- Meet info: ???
- No bus
- Arrive at race at ???
- Race starts at ???

[TBD] Monday September 29, MSCR Invitational (location TBD; consider Turville, Hamilton, Sennett)

- Meet info: ???
- Bus departs from O'Keeffe at ???
- First race starts at ???
- Bus returns to O'Keeffe at ???

Saturday October 4, Boys Kratochwill Invite Glacier Creek MS, Cross Plains

- Meet info: ???
- Bus departs from O'Keeffe at ???
- First race starts at ???
- Bus returns to O'Keeffe at ???

Friday October 10, All-City Championship (in partnership with MMSD High school event)

- Meet info: ???
- Bus departs from O'Keeffe at ???
- First race starts at ???
- Bus returns to O'Keeffe at ???

[TBD; Optional] Tuesday in mid October, Verona MS Invite

- Meet info: ???
- No bus
- Arrive at race at ???
- First race starts at ???

[TBD] Saturday in late October, Elver Park 5K trail race

- Meet info: ???
- Bus departs from O'Keeffe at ???
- Race starts at ???
- Bus returns to O'Keeffe at ???

