---
title: 2024 Race Schedule
format: pdf
---

09/07, Verona Invitational

  - Pre-season event/No bus
  - Middle school race at 11 am 
  - [race details](https://crm.pttiming.com/uploads/projects/1831/db92f55e3d463770149f85ebdb3874dd.pdf)
   
09/14, Monona Grove Middle School Invitational

  - Pre-season event/No bus
  - Middle school race at 8:30 am
  - [race details](https://wi.milesplit.com/meets/633714-monona-grove-invitational-2024)
  
9/21 Wildcat Invitational - Belleville

  - Bus leaves O'Keeffe at 8:45 am
  - Middle school race at 10:30 am
  - [race details](https://www.accuracetiming.com/files/bellcc_24.pdf)
  
09/28, MSCR Invitational @ Gillespie Middle School (101 S. Gammon Rd)

  - Bus leaves O'Keeffe at 8:45 am
  - 6th Grade race start 10 am
  - 7th Grade race start 10:45 am
  - 8th Grade race start 11:30 pm 
  
10/05, Evan Kratochwill Memorial in Cross Plains

  - Bus leaves O'Keeffe at 7:15 am
  - Middle school girls race starts at 9:05 am
  - Middle school boys race starts at 9:30 am
  - [race details](https://docs.google.com/document/d/11evPYc6JtN9KG2NJZZYJVBka61nA71iSBjD8zOuitSc/)
  - Community race available prior to start of MS races
  - NOTE: 5th graders can participate (talk with Coach John for details)

10/12, MSCR All City Invitational

  - Details pending 

10/15 (Tuesday), Verona MS Invite

  - Optional race, Not MSCR Sponsored/No bus
  - Talk with Coach John if interested
  
11/02, Madnorski/Elver 5K trail run

  - Bus leaves O'Keeffe at 7:45 am
  - 5K race start at 9 am
  - [race details](https://www.madnorski.org/elver-park-trail-run/)
  - Community race available (1K, 5K, and 10K options) for families